/******************************************************************************
 File: mkbug.h

 By: David Schwartz

 Date: August 1994

 (C) Williams Entertainment

 Mortal Kombat III Debugging
******************************************************************************/

#ifndef __mk_mkbug_h__
#define __mk_mkbug_h__

/* 
 * 	DEFINITIONS
 */


/* 
 *	RAM 
 */

/*
 *	PROTOTYPES 
 */
void debug_grid(void);
void profiler(void);
void draw_collision_box(XYTYPE *,XYTYPE *,WORD);

/*
 *	MACROS
 */

#endif /* __mk_mkbug_h__ */

